#!/usr/bin/env python3
"""Assemble the RD68011 microcode into SystemVerilog.

    python3 tools/ucode/assemble.py

Writes three generated files under rtl/gen/ and a listing under build/:

  rd68011_ucode_pkg.sv    field positions and every encoding, as localparams
  rd68011_ucode_rom.sv    micro-address -> microword, which carries the
                          request previews of its own successors
  rd68011_decode_rom.sv   opcode -> microcode entry point and its request
                          preview, as a casez
  rd68011_loop_rom.sv     opcode -> can this be a looped instruction, UM
                          table A-1, also a casez
  build/ucode.lst         the microcode, disassembled, for reading

The generated files are checked in, so a build does not need Python. Rerun this
after editing isa.py or program.py; `make ucode` does it for you and `make
ucode-check` fails if the checked-in files are stale.

Why a casez rather than a 65536-entry table: the decoder is written as an
ordered list of bit patterns, which a casez expresses directly and both FPGA and
ASIC flows turn into a few levels of logic. A full table would be 64K entries of
ROM for something that is mostly don't-cares.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
sys.path.insert(0, HERE)

import isa                                              # noqa: E402
import program                                          # noqa: E402

GEN = os.path.join(ROOT, 'rtl', 'gen')
BUILD = os.path.join(ROOT, 'build')

BANNER = ('// GENERATED by tools/ucode/assemble.py -- do not edit.\n'
          '// Source: tools/ucode/isa.py and tools/ucode/program.py.\n')


def encode(fields):
    """Pack one microword's fields into an integer."""
    val = 0
    for name, w, _ in isa.FIELDS:
        v = fields.get(name, isa.DEFAULTS[name])
        if v >= (1 << w):
            raise ValueError('%s = %d does not fit %d bits' % (name, v, w))
        val |= v << isa.lsb(name)
    return val


def resolve(words, labels, fixups, fallthrough):
    """Turn goto labels into micro-addresses and fill in fall-through."""
    for idx, field, name in fixups:
        if name not in labels:
            raise KeyError('microcode branch to unknown label %r' % name)
        words[idx][0][field] = labels[name]
    for idx in fallthrough:
        words[idx][0]['next'] = idx + 1
    return words


def fill_previews(words):
    """Give every microword the request previews of its own successors.

    Must run after resolve(), because a fall-through microword only has a
    `next` once that has filled it in. Returns the preview of every address,
    which emit_pkg and emit_decode need for the arms whose successor is not
    `next` at all.
    """
    rq = [isa.req_word(fields) for fields, _ in words]
    none = isa.req_word({})            # bus=NONE: presents no request

    def preview(addr):
        # A DECODE or RESUME microword's `next` is meaningless -- its successor
        # is the decoder's entry point or the saved micro-PC -- and the last
        # microword's fall-through runs off the end of the store.
        return rq[addr] if 0 <= addr < len(rq) else none

    for fields, _ in words:
        seq = fields.get('seq', isa.DEFAULTS['seq'])
        nxt = fields.get('next', isa.DEFAULTS['next'])
        if seq in (isa.SEQ['DECODE'], isa.SEQ['RESUME']):
            fields['rq0'] = fields['rq1'] = none
        else:
            fields['rq0'] = preview(nxt)
            # Only a COND microword can land on the odd half of the pair. For
            # everything else both halves are the same successor, which lets
            # the RTL select without testing `seq` at all.
            fields['rq1'] = (preview(nxt | 1) if seq == isa.SEQ['COND']
                             else fields['rq0'])
    return rq


def check_arms(words, rq):
    """Which conditions can steer the bus, and how many actually do.

    Reported rather than enforced. rd68011_seq.sv narrows the preview select to
    the conditions listed here, so this is the evidence for that narrowing, and
    a microcode change that gives some other condition two different bus
    requests has to show up as a build-time failure rather than as a wrong
    address on the pins.
    """
    names = {v: k for k, v in isa.COND.items()}
    steering = set()
    for i, (fields, _) in enumerate(words):
        if fields.get('seq') != isa.SEQ['COND']:
            continue
        nxt = fields['next']
        if rq[nxt] != rq[nxt | 1]:
            steering.add(names[fields.get('cond', isa.DEFAULTS['cond'])])
    return steering


def check_patterns(patterns):
    """Report any opcode pattern completely shadowed by an earlier one.

    An ordered casez is only readable if the order is doing work you meant. A
    pattern that can never match is a mistake; one that is partly shadowed is
    the point (BRA.W before BRA.B), so only total shadowing is an error.
    """
    def matches(spec, other):
        """Every opcode `other` matches, does `spec` also match?"""
        for a, b in zip(spec, other):
            if a == '-':
                continue
            if b == '-':
                return False
            if a != b:
                return False
        return True

    problems = []
    for i, (pat, _, mnem) in enumerate(patterns):
        for pat2, _, mnem2 in patterns[:i]:
            if matches(pat2, pat):
                problems.append('%s (%s) can never match: %s (%s) covers it'
                                % (mnem, pat, mnem2, pat2))
    return problems


def emit_pkg(labels=None, rq=None):
    out = [BANNER, '',
           '// The microword layout. Every field position and every encoding',
           '// the microcode can use, so the RTL and the microcode cannot',
           '// drift apart.', '',
           'package rd68011_ucode_pkg;', '']
    out.append('  localparam int UW    = %d;   // microword width' % isa.width())
    out.append('  localparam int RQW   = %d;   // request preview width'
               % isa.req_width())
    out.append('  localparam int UADDR = %d;   // micro-address width'
               % isa.UADDR_BITS)
    out.append('')
    out.append('  // The request preview -- tools/ucode/isa.py REQ_FIELDS.')
    for name, w, _ in isa.REQ_FIELDS:
        out.append('  localparam int R_%s_LSB = %d;' % (name.upper(),
                                                        isa.req_lsb(name)))
        out.append('  localparam int R_%s_W   = %d;' % (name.upper(), w))
    out.append('')
    for name, w, enc in isa.FIELDS:
        out.append('  // %s: %d bits at %d' % (name, w, isa.lsb(name)))
        out.append('  localparam int U_%s_LSB = %d;' % (name.upper(), isa.lsb(name)))
        out.append('  localparam int U_%s_W   = %d;' % (name.upper(), w))
        if enc:
            for k in sorted(enc, key=lambda k: enc[k]):
                out.append('  localparam logic [%d:0] U_%s_%s = %d\'d%d;'
                           % (w - 1, name.upper(), k, w, enc[k]))
        out.append('')
    if labels:
        out.append('  // Entry points the RTL needs by name.')
        for name in ('reset', 'illegal', 'interrupt', 'trace',
                     'buserr', 'addrerr', 'halted', 'spurious',
                     'dbcc_loop'):
            out.append("  localparam logic [UADDR-1:0] ENTRY_%s = %d'd%d;"
                       % (name.upper(), isa.UADDR_BITS, labels[name]))
        out.append('')
    if labels and rq is not None:
        w = isa.req_width()
        nib = (w + 3) // 4
        out.append('  // The request previews of those entry points. Every arm')
        out.append('  // of the sequencer\'s next-microword choice needs one,')
        out.append('  // and the arms that go to a fixed entry point can have')
        out.append('  // it as a constant. PREV_NONE presents no request at')
        out.append('  // all -- it is what a RESUME arm carries, and what the')
        out.append('  // rq0/rq1 fields of a microword whose successor is not')
        out.append('  // `next` are filled with.')
        for name in ('reset', 'illegal', 'interrupt', 'trace',
                     'buserr', 'addrerr', 'halted', 'spurious',
                     'dbcc_loop'):
            out.append("  localparam logic [RQW-1:0] PREV_%s = %d'h%0*x;"
                       % (name.upper(), w, nib, rq[labels[name]]))
        out.append("  localparam logic [RQW-1:0] PREV_NONE = %d'h%0*x;"
                   % (w, nib, isa.req_word({})))
        out.append('')
    out.append('endpackage')
    out.append('')
    return '\n'.join(out)


def emit_urom(words):
    w = isa.width()
    nibbles = (w + 3) // 4
    out = [BANNER, '',
           '// The microcode store: micro-address to microword.', '',
           'module rd68011_ucode_rom (',
           '    input  logic [rd68011_ucode_pkg::UADDR-1:0] addr,',
           '    output logic [rd68011_ucode_pkg::UW-1:0]    uw',
           ');', '',
           '  always_comb begin',
           '    case (addr)']
    for i, (fields, comment) in enumerate(words):
        val = encode(fields)
        line = ("      %d'd%-3d: uw = %d'h%0*x;" %
                (isa.UADDR_BITS, i, w, nibbles, val))
        if comment:
            line += '  // %s' % comment
        out.append(line)
    out.append("      default: uw = %d'h0;" % w)
    out.append('    endcase')
    out.append('  end')
    out.append('')
    out.append('endmodule')
    out.append('')
    return '\n'.join(out)


def emit_decode(patterns, labels, rq):
    w = isa.req_width()
    nib = (w + 3) // 4
    ndistinct = len({rq[labels[t]] for _, t, _ in patterns})
    out = [BANNER, '',
           '// Opcode to microcode entry point, and that entry point\'s',
           '// request preview.',
           '//',
           '// Ordered: the first matching pattern wins, which is how forms',
           '// distinguished only by a field value -- BRA.W is BRA.B with a',
           '// displacement byte of zero -- are separated here rather than by',
           '// a run-time test in the microcode.',
           '//',
           '// The preview comes out of here rather than out of a second store',
           '// read at `entry`, which is what used to happen and what made the',
           '// decoder and that store a chain of two lookups inside half a',
           '// clock. It is nearly free: across all the patterns there are only',
           '// %d distinct preview values.' % ndistinct,
           '//',
           '// `illegal` is asserted for anything with no pattern.', '',
           'module rd68011_decode_rom (',
           '    input  logic                 [15:0] op,',
           '    output logic [rd68011_ucode_pkg::UADDR-1:0] entry,',
           '    output logic [rd68011_ucode_pkg::RQW-1:0]   prev,',
           '    output logic                        illegal',
           ');', '',
           '  always_comb begin',
           '    illegal = 1\'b0;',
           '    casez (op)']
    for pat, target, mnem in patterns:
        if target not in labels:
            raise KeyError('opcode %s targets unknown label %r' % (mnem, target))
        svpat = pat.replace('-', '?')
        out.append("      16'b%s: begin entry = %d'd%-4d; prev = %d'h%0*x; end  // %s"
                   % (svpat, isa.UADDR_BITS, labels[target],
                      w, nib, rq[labels[target]], mnem))
    out.append('      default: begin')
    out.append("        entry   = %d'd%d;  // illegal" % (isa.UADDR_BITS,
                                                          labels['illegal']))
    out.append("        prev    = %d'h%0*x;" % (w, nib, rq[labels['illegal']]))
    out.append("        illegal = 1'b1;")
    out.append('      end')
    out.append('    endcase')
    out.append('  end')
    out.append('')
    out.append('endmodule')
    out.append('')
    return '\n'.join(out)


def emit_loop(loop_patterns):
    """Opcode to "can this be the looped instruction" -- UM appendix A."""
    out = [BANNER, '',
           '// The loop mode instruction table, UM table A-1.',
           '//',
           '// Every one-word instruction whose memory operands use only (An),',
           '// (An)+ and -(An): with no instruction fetches happening there is',
           '// nowhere for an extension word to come from. The reasoning behind',
           '// two readings of that table is in tools/ucode/program.py.', '',
           'module rd68011_loop_rom (',
           '    input  logic [15:0] op,',
           '    output logic        is_loop',
           ');', '',
           '  always_comb begin',
           '    casez (op)']
    seen = {}
    for pat, mnem in loop_patterns:
        if pat in seen:
            continue
        seen[pat] = mnem
        out.append("      16'b%s: is_loop = 1'b1;  // %s"
                   % (pat.replace('-', '?'), mnem))
    out.append("      default: is_loop = 1'b0;")
    out.append('    endcase')
    out.append('  end')
    out.append('')
    out.append('endmodule')
    out.append('')
    return '\n'.join(out)


def emit_listing(words, labels, patterns):
    rev = {}
    for name, addr in labels.items():
        rev.setdefault(addr, []).append(name)

    enc_names = {}
    for name, _, enc in isa.FIELDS:
        if enc:
            enc_names[name] = {v: k for k, v in enc.items()}

    out = ['RD68011 microcode listing',
           '=========================',
           '',
           'Generated by tools/ucode/assemble.py. %d microwords of %d bits, '
           '%d opcode patterns.' % (len(words), isa.width(), len(patterns)),
           '']
    for i, (fields, comment) in enumerate(words):
        for name in sorted(rev.get(i, [])):
            out.append('%s:' % name)
        parts = []
        for name, _, _ in isa.FIELDS:
            # rq0/rq1 are not written by the microprogram: they are the
            # successors' own fields, copied here by fill_previews so the
            # sequencer has them a clock early. Printing them says nothing a
            # reader cannot get by looking at the successor, and says it on
            # every line.
            if name in ('rq0', 'rq1'):
                continue
            v = fields.get(name, isa.DEFAULTS[name])
            if v == isa.DEFAULTS[name] and name != 'next':
                continue
            if name in enc_names:
                parts.append('%s=%s' % (name, enc_names[name].get(v, v)))
            else:
                parts.append('%s=%d' % (name, v))
        out.append('  %3d  %-64s %s' % (i, ' '.join(parts),
                                        ('; ' + comment) if comment else ''))
    out.append('')
    out.append('Opcode patterns, in priority order')
    out.append('----------------------------------')
    for pat, target, mnem in patterns:
        out.append('  %s  %-10s -> %s (%d)' % (pat, mnem, target,
                                               labels[target]))
    out.append('')
    return '\n'.join(out)


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    old = None
    if os.path.exists(path):
        with open(path) as f:
            old = f.read()
    if old == text:
        return False
    with open(path, 'w') as f:
        f.write(text)
    return True


def main():
    isa.check()
    words, labels, fixups, patterns, fallthrough = program.build()
    words = resolve(words, labels, fixups, fallthrough)

    problems = check_patterns(patterns)
    if problems:
        for p in problems:
            print('error: ' + p)
        return 1

    if len(words) > (1 << isa.UADDR_BITS):
        print('error: %d microwords will not fit %d bits of address'
              % (len(words), isa.UADDR_BITS))
        return 1

    # Conditional branches land on an even/odd pair, so the target has to be
    # even for "next, or next+1 if the condition holds" to mean anything.
    for i, (fields, _) in enumerate(words):
        if fields.get('seq') == isa.SEQ['COND'] and fields.get('next', 0) % 2:
            print('error: microword %d branches conditionally to an odd '
                  'address' % i)
            return 1

    # Every microword's own successors' previews, once `next` is known.
    rq = fill_previews(words)
    steering = check_arms(words, rq)

    changed = []
    for name, text in [
            ('rtl/gen/rd68011_ucode_pkg.sv', emit_pkg(labels, rq)),
            ('rtl/gen/rd68011_ucode_rom.sv', emit_urom(words)),
            ('rtl/gen/rd68011_decode_rom.sv', emit_decode(patterns, labels, rq)),
            ('rtl/gen/rd68011_loop_rom.sv', emit_loop(program.loop_patterns)),
            ('build/ucode.lst', emit_listing(words, labels, patterns))]:
        if write(os.path.join(ROOT, name), text):
            changed.append(name)

    stale = os.path.join(ROOT, 'rtl/gen/rd68011_ureq_rom.sv')
    if os.path.exists(stale):
        os.remove(stale)
        changed.append('rtl/gen/rd68011_ureq_rom.sv (removed)')

    print('%d microwords, %d bits wide (%d of request preview), '
          '%d opcode patterns, %d loop mode patterns'
          % (len(words), isa.width(), isa.req_width(), len(patterns),
             len(program.loop_patterns)))
    print('conditions that steer a bus request: %s'
          % (', '.join(sorted(steering)) or 'none'))
    if changed:
        print('updated: ' + ', '.join(changed))
    else:
        print('generated files already up to date')

    if '--check' in sys.argv and any(c.startswith('rtl/') for c in changed):
        print('error: checked-in generated files were stale')
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
