#!/usr/bin/env python3
"""Assemble the RD68011 microcode into SystemVerilog.

    python3 tools/ucode/assemble.py

Writes three generated files under rtl/gen/ and a listing under build/:

  rd68011_ucode_pkg.sv    field positions and every encoding, as localparams
  rd68011_ucode_rom.sv    micro-address -> microword, which carries the
                          request previews of its own successors
  rd68011_decode_rom.sv   opcode -> microcode entry point and its request
                          preview, as a casez
  rd68011_loop_rom.sv     opcode -> can this be a looped instruction, UM
                          table A-1, also a casez
  build/ucode.lst         the microcode, disassembled, for reading

The generated files are checked in, so a build does not need Python. Rerun this
after editing isa.py or program.py; `make ucode` does it for you and `make
ucode-check` fails if the checked-in files are stale.

Why a casez rather than a 65536-entry table: the decoder is written as an
ordered list of bit patterns, which a casez expresses directly and both FPGA and
ASIC flows turn into a few levels of logic. A full table would be 64K entries of
ROM for something that is mostly don't-cares.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
sys.path.insert(0, HERE)

import isa                                              # noqa: E402
import program                                          # noqa: E402

GEN = os.path.join(ROOT, 'rtl', 'gen')
BUILD = os.path.join(ROOT, 'build')

BANNER = ('// GENERATED by tools/ucode/assemble.py -- do not edit.\n'
          '// Source: tools/ucode/isa.py and tools/ucode/program.py.\n')


def encode(fields):
    """Pack one microword's fields into an integer."""
    val = 0
    for name, w, _ in isa.FIELDS:
        v = fields.get(name, isa.DEFAULTS[name])
        if v >= (1 << w):
            raise ValueError('%s = %d does not fit %d bits' % (name, v, w))
        val |= v << isa.lsb(name)
    return val


def resolve(words, labels, fixups, fallthrough):
    """Turn goto labels into micro-addresses and fill in fall-through."""
    for idx, field, name in fixups:
        if name not in labels:
            raise KeyError('microcode branch to unknown label %r' % name)
        words[idx][0][field] = labels[name]
    for idx in fallthrough:
        words[idx][0]['next'] = idx + 1
    return words


def fill_previews(words):
    """Give every microword the request previews of its own successors.

    Must run after resolve(), because a fall-through microword only has a
    `next` once that has filled it in. Returns the preview of every address,
    which emit_pkg and emit_decode need for the arms whose successor is not
    `next` at all.
    """
    rq = [isa.req_word(fields) for fields, _ in words]
    none = isa.req_word({})            # bus=NONE: presents no request

    def preview(addr):
        # A DECODE or RESUME microword's `next` is meaningless -- its successor
        # is the decoder's entry point or the saved micro-PC -- and the last
        # microword's fall-through runs off the end of the store.
        return rq[addr] if 0 <= addr < len(rq) else none

    for fields, _ in words:
        seq = fields.get('seq', isa.DEFAULTS['seq'])
        nxt = fields.get('next', isa.DEFAULTS['next'])
        if seq in (isa.SEQ['DECODE'], isa.SEQ['RESUME']):
            fields['rq0'] = fields['rq1'] = none
        else:
            fields['rq0'] = preview(nxt)
            # Only a COND microword can land on the odd half of the pair. For
            # everything else both halves are the same successor, which lets
            # the RTL select without testing `seq` at all.
            fields['rq1'] = (preview(nxt | 1) if seq == isa.SEQ['COND']
                             else fields['rq0'])
    return rq


def check_ir_dst(words, rq):
    """Which microwords write ir from the ALU, and what may follow them.

    rd68011_seq.sv computes the next microword's address register from
    `ir_pipe_nxt`, which carries the prefetch pipe's own value of ir and not the
    U_DST_IR write that RTE uses to reload it out of a format $8 frame. That is
    what keeps the ALU and the shifter out of the address unit's fan-in, and it
    was worth 1.22 ns -- but it is only correct while no successor of such a
    microword addresses through a field of the opcode being written.

    Nothing in the RTL can see that, so it is said here, exactly as
    check_arms says the bus-steering conditions.
    """
    bad = []
    for i, (fields, _) in enumerate(words):
        if fields.get('dst') != isa.DST['IR']:
            continue
        if fields.get('lp') == isa.LP['ENTER']:
            bad.append('microword %d writes ir from the ALU and enters loop '
                       'mode. rd68011_seq.sv reads the loop ROM at '
                       '`ir_pipe_nxt`, which does not carry that write.' % i)
        succ = [fields['next']]
        if fields.get('seq') == isa.SEQ['COND']:
            succ.append(fields['next'] | 1)
        for t in succ:
            if t >= len(rq):
                continue
            r = rq[t]
            get = lambda n, w: (r >> isa.req_lsb(n)) & ((1 << w) - 1)
            if get('bus', 3) == isa.BUS['NONE']:
                continue
            if get('aeasel', 2) == isa.AEASEL['SP']:
                continue
            bad.append(
                'microword %d writes ir from the ALU and its successor %d '
                'addresses through a register field of the opcode. '
                'rd68011_seq.sv computes the next microword\'s address '
                'register from `ir_pipe_nxt`, which does not carry that write, '
                'so this would address through the old opcode. Either give the '
                'successor aeasel=SP, or restore the U_DST_IR arm to n_ea_reg '
                'in rd68011_seq.sv -- and re-measure, because that arm is what '
                'puts the ALU and the shifter in the address unit\'s fan-in.'
                % (i, t))
    return bad


def check_arms(words, rq):
    """Which conditions actually decide what the bus does next.

    A conditional microword only steers the bus if its two successors present
    different requests. rd68011_seq.sv selects the preview on exactly the
    conditions in isa.BUS_STEERING_CONDS and no others, which is what keeps the
    ALU out of the bus request's fan-in; if the microprogram ever needs another
    one, that has to be a build failure rather than a wrong address on the pins.
    """
    names = {v: k for k, v in isa.COND.items()}
    steering = {}
    for i, (fields, _) in enumerate(words):
        if fields.get('seq') != isa.SEQ['COND']:
            continue
        nxt = fields['next']
        if rq[nxt] != rq[nxt | 1]:
            steering.setdefault(
                names[fields.get('cond', isa.DEFAULTS['cond'])], []).append(i)

    problems = []
    for cond in sorted(set(steering) - set(isa.BUS_STEERING_CONDS)):
        where = steering[cond]
        problems.append(
            'microword%s %s branch%s on %s to successors that present '
            'different bus requests. rd68011_seq.sv only steers the request on '
            '%s, so this would put the wrong address on the pins. Either give '
            'both arms the same request, or add %s to isa.BUS_STEERING_CONDS '
            'and widen prev_sel in rd68011_seq.sv to match -- and re-measure, '
            'because %s is what decides whether the ALU is in the request path.'
            % ('' if len(where) == 1 else 's',
               ', '.join(str(w) for w in where[:8]) +
               ('' if len(where) <= 8 else ', ...'),
               'es' if len(where) == 1 else '',
               cond, ' and '.join(isa.BUS_STEERING_CONDS) or 'nothing',
               cond, cond))
    return sorted(steering), problems


def check_patterns(patterns):
    """Report any opcode pattern completely shadowed by an earlier one.

    An ordered casez is only readable if the order is doing work you meant. A
    pattern that can never match is a mistake; one that is partly shadowed is
    the point (BRA.W before BRA.B), so only total shadowing is an error.
    """
    def matches(spec, other):
        """Every opcode `other` matches, does `spec` also match?"""
        for a, b in zip(spec, other):
            if a == '-':
                continue
            if b == '-':
                return False
            if a != b:
                return False
        return True

    problems = []
    for i, (pat, _, mnem) in enumerate(patterns):
        for pat2, _, mnem2 in patterns[:i]:
            if matches(pat2, pat):
                problems.append('%s (%s) can never match: %s (%s) covers it'
                                % (mnem, pat, mnem2, pat2))
    return problems


def emit_pkg(labels=None, rq=None, tab=None):
    out = [BANNER, '',
           '// The microword layout. Every field position and every encoding',
           '// the microcode can use, so the RTL and the microcode cannot',
           '// drift apart.', '',
           'package rd68011_ucode_pkg;', '']
    out.append('  localparam int UW    = %d;   // microword width' % isa.width())
    out.append('  localparam int RQW   = %d;   // request preview width'
               % isa.req_width())
    out.append('  localparam int UADDR = %d;   // micro-address width'
               % isa.UADDR_BITS)
    if tab is not None:
        # The store's own word, and the two tables it indexes. See
        # tools/ucode/assemble.py build_tables for what is in them and why.
        out.append('  localparam int UCTL_W = %d;   // control field width'
                   % CTL_W)
        out.append('  localparam int URQ_W  = %d;   // both request previews'
                   % RQ_W)
        out.append('  localparam int UCTL_N = %d;   // distinct control patterns'
                   % len(tab['ctl']))
        out.append('  localparam int URQ_N  = %d;   // distinct preview pairs'
                   % len(tab['rq']))
        out.append('  localparam int UL1    = %d;   // stored word: index, '
                   'index, successor'
                   % (isa.UADDR_BITS + tab['ctl_w'] + tab['rq_w']))
    out.append('')
    out.append('  // The request preview -- tools/ucode/isa.py REQ_FIELDS.')
    for name, w, _ in isa.REQ_FIELDS:
        out.append('  localparam int R_%s_LSB = %d;' % (name.upper(),
                                                        isa.req_lsb(name)))
        out.append('  localparam int R_%s_W   = %d;' % (name.upper(), w))
    out.append('')
    for name, w, enc in isa.FIELDS:
        out.append('  // %s: %d bits at %d' % (name, w, isa.lsb(name)))
        out.append('  localparam int U_%s_LSB = %d;' % (name.upper(), isa.lsb(name)))
        out.append('  localparam int U_%s_W   = %d;' % (name.upper(), w))
        if enc:
            for k in sorted(enc, key=lambda k: enc[k]):
                out.append('  localparam logic [%d:0] U_%s_%s = %d\'d%d;'
                           % (w - 1, name.upper(), k, w, enc[k]))
        out.append('')
    if labels:
        out.append('  // Entry points the RTL needs by name.')
        for name in ('reset', 'illegal', 'interrupt', 'trace',
                     'buserr', 'addrerr', 'halted', 'spurious',
                     'dbcc_loop'):
            out.append("  localparam logic [UADDR-1:0] ENTRY_%s = %d'd%d;"
                       % (name.upper(), isa.UADDR_BITS, labels[name]))
        out.append('')
    if labels and rq is not None:
        w = isa.req_width()
        nib = (w + 3) // 4
        out.append('  // The request previews of those entry points. Every arm')
        out.append('  // of the sequencer\'s next-microword choice needs one,')
        out.append('  // and the arms that go to a fixed entry point can have')
        out.append('  // it as a constant. PREV_NONE presents no request at')
        out.append('  // all -- it is what a RESUME arm carries, and what the')
        out.append('  // rq0/rq1 fields of a microword whose successor is not')
        out.append('  // `next` are filled with.')
        for name in ('reset', 'illegal', 'interrupt', 'trace',
                     'buserr', 'addrerr', 'halted', 'spurious',
                     'dbcc_loop'):
            out.append("  localparam logic [RQW-1:0] PREV_%s = %d'h%0*x;"
                       % (name.upper(), w, nib, rq[labels[name]]))
        out.append("  localparam logic [RQW-1:0] PREV_NONE = %d'h%0*x;"
                   % (w, nib, isa.req_word({})))
        out.append('')
    out.append('endpackage')
    out.append('')
    return '\n'.join(out)


# ---------------------------------------------------------------------------
# The microword's two levels
#
# 6674 microwords of 146 bits is 974,404 bits, and almost none of it is
# distinct. The successor address is: 6313 of the 8192 addresses name a
# different one. Everything else is not -- the 91 control bits take 600
# distinct values across the whole microprogram and the two request previews,
# taken as the pair they always travel as, take 126.
#
# So the store holds an address and two indices, 30 bits, and two small tables
# hold the patterns. 260,142 bits rather than 974,404, which is 3.75x, and on
# the MAX 10 it is the difference between 146 M9K blocks and 30 -- 80 % of the
# part's memory against 16 %. doc/size-and-speed.md measures what that was
# worth.
#
# The second level cannot be registered and is not meant to be: its index only
# exists after the store's own register, and making the store combinational is
# what would stop it being a memory. It is combinational logic in front of the
# microword's consumers, and that is the cost being measured against the
# saving.
#
# On an ASIC, where the store is logic either way, the same 3.75x applies to
# the logic directly.

NEXT_W  = isa.UADDR_BITS
CTL_LSB = NEXT_W
RQ_LSB  = isa.lsb('rq0')
CTL_W   = RQ_LSB - CTL_LSB
RQ_W    = isa.width() - RQ_LSB


def idx_bits(n):
    """Bits needed to name n table entries."""
    b = 1
    while (1 << b) < n:
        b += 1
    return b


def split_word(val):
    """One microword as (successor, control pattern, preview pair)."""
    return (val & ((1 << NEXT_W) - 1),
            (val >> CTL_LSB) & ((1 << CTL_W) - 1),
            val >> RQ_LSB)


def build_tables(words):
    """Intern every control pattern and preview pair, in first-seen order.

    The unmapped-address default is interned too, so the arm that answers for
    it has indices like any other word.
    """
    ctl_tab, ctl_of = [], {}
    rq_tab, rq_of = [], {}
    l1 = []
    for val in [encode(f) for f, _ in words] + [encode(isa.DEFAULTS)]:
        nxt, ctl, rq = split_word(val)
        if ctl not in ctl_of:
            ctl_of[ctl] = len(ctl_tab)
            ctl_tab.append(ctl)
        if rq not in rq_of:
            rq_of[rq] = len(rq_tab)
            rq_tab.append(rq)
        l1.append((nxt, ctl_of[ctl], rq_of[rq]))
    return {'ctl': ctl_tab, 'rq': rq_tab, 'l1': l1[:-1], 'default': l1[-1],
            'ctl_w': idx_bits(len(ctl_tab)), 'rq_w': idx_bits(len(rq_tab))}


def check_two_level(words, tab):
    """Rebuild every one of the 8192 addresses and insist it is unchanged.

    Exhaustive, and cheap, and the same standard check_disjoint sets for the
    decoder: a table that does not reconstruct the microword it was built from
    is a wrong netlist, not a slow one.
    """
    want = [encode(f) for f, _ in words]
    dflt = encode(isa.DEFAULTS)
    for addr in range(1 << isa.UADDR_BITS):
        if addr < len(tab['l1']):
            nxt, ci, ri = tab['l1'][addr]
            expect = want[addr]
        else:
            nxt, ci, ri = tab['default']
            expect = dflt
        got = nxt | (tab['ctl'][ci] << CTL_LSB) | (tab['rq'][ri] << RQ_LSB)
        if got != expect:
            return ['microword %d rebuilds as %x, not %x' % (addr, got, expect)]
    return []


def emit_urom(words, tab):
    """The store: one address, two indices, and a registered read.

    A registered case is what both Vivado and Quartus infer a block memory
    from, and it is the only form available -- an array would have to be
    filled by an initial block or $readmemh, which CLAUDE.md bars and
    tools/reset_audit.py checks for.

    The attributes say which memory, and they are not decoration. Vivado's own
    report calls its choice preliminary and its timing optimisation may reverse
    it later: building the core with LOOP_BUF_WORDS at 16 was enough to make it
    do so, and the store came back as 1900 LUTs with no message saying anything
    had been declined. What the store is made of should not turn on unrelated
    logic somewhere else in the design. Both attributes are ignored by a tool
    that does not know them, so an ASIC flow still synthesises the same case as
    logic and the two tables below shrink it there just as much.

    The read is registered and the address is upc_nxt rather than upc, so the
    word this holds is the same word at the same time -- see the note in
    rd68011_seq.sv where it is instantiated.

    l1_q takes no reset. It is the one register in the design that does not,
    and tools/reset_audit.py names it and says why.
    """
    cw, rw = tab['ctl_w'], tab['rq_w']
    l1w = NEXT_W + cw + rw
    nib = (l1w + 3) // 4

    def word(nxt, ci, ri):
        return nxt | (ci << NEXT_W) | (ri << (NEXT_W + cw))

    out = [BANNER, '',
           '// The microcode store: micro-address to microword.', '',
           'module rd68011_ucode_rom (',
           '    input  logic                                clk,',
           '    input  logic [rd68011_ucode_pkg::UADDR-1:0] addr,',
           '    output logic [rd68011_ucode_pkg::UW-1:0]    uw',
           ');', '',
           '  // { preview index, control index, successor }',
           '  (* rom_style = "block", ramstyle = "M9K" *)',
           '  logic [rd68011_ucode_pkg::UL1-1:0] l1_q;', '',
           '  always_ff @(posedge clk) begin',
           '    case (addr)']
    for i, (fields, comment) in enumerate(words):
        nxt, ci, ri = tab['l1'][i]
        line = ("      %d'd%-3d: l1_q <= %d'h%0*x;"
                % (isa.UADDR_BITS, i, l1w, nib, word(nxt, ci, ri)))
        if comment:
            line += '  // %s' % comment
        out.append(line)
    # The default arm is not "impossible", it is "unmapped": the store holds
    # fewer microwords than a 13-bit address can name. Nothing the assembler
    # emits targets one of the gaps, but a micro-address also arrives from
    # outside -- RTE restores one out of a format $8 frame, and while the frame
    # format and version are checked the micro-address in it is not.
    #
    # So this has to be a microword that does nothing, and all-zeros is not
    # one: BUS['READ'] is 0, because the field doubles as rd68011_pkg's
    # cycle_kind_e, so a zero microword asks for a read at the program counter
    # in program space. The defaults do nothing and go to the reset entry.
    out.append("      // Unmapped. The defaults: no bus request, and the reset")
    out.append("      // entry next. See tools/ucode/assemble.py emit_urom.")
    out.append("      default: l1_q <= %d'h%0*x;"
               % (l1w, nib, word(*tab['default'])))
    out.append('    endcase')
    out.append('  end')
    out.append('')
    out.append('  logic [rd68011_ucode_pkg::UCTL_W-1:0] ctl;')
    out.append('  logic [rd68011_ucode_pkg::URQ_W-1:0]  rqp;')
    out.append('')
    out.append('  rd68011_uctl_rom u_ctl (')
    out.append('      .idx (l1_q[%d:%d]), .ctl (ctl));'
               % (NEXT_W + cw - 1, NEXT_W))
    out.append('  rd68011_urq_rom u_rq (')
    out.append('      .idx (l1_q[%d:%d]), .rq  (rqp));'
               % (l1w - 1, NEXT_W + cw))
    out.append('')
    out.append('  assign uw = {rqp, ctl, l1_q[%d:0]};' % (NEXT_W - 1))
    out.append('')
    out.append('endmodule')
    out.append('')
    return '\n'.join(out)


def emit_table(module, port, tab, entries, iw, vw, what):
    """One second-level table: index to bit pattern, combinational."""
    nib = (vw + 3) // 4
    out = [BANNER, '',
           '// %s' % what, '',
           'module %s (' % module,
           '    input  logic [%d:0] idx,' % (iw - 1),
           '    output logic [%d:0] %s' % (vw - 1, port),
           ');', '',
           '  always_comb begin',
           '    case (idx)']
    for i, v in enumerate(entries):
        out.append("      %d'd%-3d: %s = %d'h%0*x;" % (iw, i, port, vw, nib, v))
    # Every index the store can hold is in the table above, so this answers for
    # nothing the design reaches. It is here because an unassigned arm is a
    # latch to yosys and an error to Verilator, and because the pattern the
    # unmapped microword uses is the safe one to repeat.
    out.append('      // No index reaches this. The unmapped microword\'s own,')
    out.append('      // so a case that cannot happen does nothing if it does.')
    out.append("      default: %s = %d'h%0*x;" % (port, vw, nib, entries[tab]))
    out.append('    endcase')
    out.append('  end')
    out.append('')
    out.append('endmodule')
    out.append('')
    return '\n'.join(out)




def _norm(pat):
    return pat.replace('-', '?')


def _cube(pat):
    """A pattern as (care, value) integers, for a fast overlap test."""
    care = val = 0
    for ch in pat:
        care <<= 1
        val <<= 1
        if ch != '?':
            care |= 1
            if ch == '1':
                val |= 1
    return care, val


def _overlaps(a, b):
    both = a[0] & b[0]
    return (a[1] & both) == (b[1] & both)


def _encodings(pat):
    """Every opcode the pattern matches.

    By enumerating the don't-care bits rather than the whole 16-bit space: the
    patterns cover about 55000 encodings between them, so this is thousands of
    steps where testing every opcode against every pattern is ninety million.
    """
    free = [15 - i for i, ch in enumerate(pat) if ch == '?']
    base = 0
    for i, ch in enumerate(pat):
        if ch == '1':
            base |= 1 << (15 - i)
    for m in range(1 << len(free)):
        op = base
        for b, bit in enumerate(free):
            if (m >> b) & 1:
                op |= 1 << bit
        yield op


def cube_minus(p, q):
    """The encodings matching pattern `p` but not pattern `q`, as patterns.

    Both are sixteen characters of '0', '1' and '?'. The result is a set of
    disjoint patterns whose union is exactly p minus q: for each bit that q
    cares about and p does not, one pattern that pins that bit the other way
    from q, with the bits before it pinned q's way. Empty when q covers p.
    """
    out = []
    cur = list(p)
    for i, (a, b) in enumerate(zip(p, q)):
        if b != '?' and a == '?':
            piece = list(cur)
            piece[i] = '0' if b == '1' else '1'
            out.append(''.join(piece))
            cur[i] = b
    return out


def make_disjoint(patterns):
    """The same decode table with no pattern overlapping an earlier one.

    The source in program.py is an ordered list, because that is the readable
    way to say that BRA.W is BRA.B with a displacement byte of zero. Ordered is
    not how it wants to be *synthesised*, though: "the first match wins" is a
    priority chain, and a tool that builds it literally rather than flattening
    it produces one. Quartus does exactly that -- doc/implementation.md has the
    measurement -- so the order is resolved here instead, once, in Python.

    Only the branch group actually overlaps; everything else passes through
    untouched. The cost is that `casez` cannot say "not zero", so a byte
    displacement that must be non-zero becomes several patterns and a Bcc that
    must not be BRA or BSR becomes one per remaining condition.
    """
    out = []
    earlier = []                        # (pattern, cube) already covered
    for pat, target, mnem in patterns:
        pat = _norm(pat)
        pieces = [(pat, _cube(pat))]
        for qpat, qcube in earlier:
            nxt = []
            for piece, pcube in pieces:
                if not _overlaps(pcube, qcube):
                    nxt.append((piece, pcube))
                    continue
                for r in cube_minus(piece, qpat):
                    nxt.append((r, _cube(r)))
            pieces = nxt
            if not pieces:
                break
        for piece, _ in pieces:
            out.append((piece, target, mnem))
        earlier.append((pat, _cube(pat)))
    return out


def check_disjoint(ordered, parallel):
    """Prove the two tables decode all 65536 opcodes the same way.

    Cheap, exhaustive, and the only thing standing between a bug in
    make_disjoint and a processor that decodes one opcode wrongly. It also
    proves the result really is disjoint, which is what lets the emitted case
    say `unique`.
    """
    want = {}
    for pat, target, _ in ordered:
        for op in _encodings(_norm(pat)):
            want.setdefault(op, target)

    got = {}
    for pat, target, mnem in parallel:
        for op in _encodings(_norm(pat)):
            if op in got:
                raise AssertionError(
                    'opcode %04x matches two parallel patterns: %s and %s'
                    % (op, got[op][1], mnem))
            got[op] = (target, mnem)

    if set(want) != set(got):
        only = sorted(set(want) ^ set(got))[:4]
        raise AssertionError('the two tables cover different opcodes: %s'
                             % ' '.join('%04x' % o for o in only))
    for op, target in want.items():
        if got[op][0] != target:
            raise AssertionError('opcode %04x: ordered says %r, parallel %r'
                                 % (op, target, got[op][0]))


def emit_decode(patterns, labels, rq):
    w = isa.req_width()
    nib = (w + 3) // 4
    ndistinct = len({rq[labels[t]] for _, t, _ in patterns})
    parallel = make_disjoint(patterns)
    check_disjoint(patterns, parallel)
    out = [BANNER, '',
           '// Opcode to microcode entry point, and that entry point\'s',
           '// request preview.',
           '//',
           '// No pattern here overlaps another, so the order of the arms does',
           '// not matter. The source in tools/ucode/program.py *is* ordered --',
           '// the first match wins, which is how forms distinguished only by a',
           '// field value are separated there rather than by a run-time test in',
           '// the microcode, BRA.W being BRA.B with a displacement byte of zero',
           '// -- and assemble.py resolves that order into disjoint patterns',
           '// here, proving over all 65536 opcodes that the two decode alike.',
           '//',
           '// Because a casez cannot say "not zero", the branch group is the',
           ('// one that pays for it: %d patterns become %d. Every other'
            % (len(patterns), len(parallel))),
           '// pattern passes through untouched.',
           '//',
           '// Why bother, when the first match winning is what the hardware',
           '// wants: "ordered" synthesises as a priority chain unless the tool',
           '// flattens it, and not every tool does. Quartus builds it as',
           '// written -- doc/implementation.md has that measurement.',
           '//',
           '// The preview comes out of here rather than out of a second store',
           '// read at `entry`, which would make the decoder and that store a',
           '// chain of two lookups inside half a clock. It is nearly free:',
           '// across all the patterns there are only %d distinct' % ndistinct,
           '// preview values.',
           '//',
           '// `illegal` is asserted for anything with no pattern.', '',
           'module rd68011_decode_rom (',
           '    input  logic                 [15:0] op,',
           '    output logic [rd68011_ucode_pkg::UADDR-1:0] entry,',
           '    output logic [rd68011_ucode_pkg::RQW-1:0]   prev,',
           '    output logic                        illegal',
           ');', '',
           '  always_comb begin',
           '    illegal = 1\'b0;',
           '    casez (op)']
    for pat, target, mnem in parallel:
        if target not in labels:
            raise KeyError('opcode %s targets unknown label %r' % (mnem, target))
        out.append("      16'b%s: begin entry = %d'd%-4d; prev = %d'h%0*x; end  // %s"
                   % (pat, isa.UADDR_BITS, labels[target],
                      w, nib, rq[labels[target]], mnem))
    out.append('      default: begin')
    out.append("        entry   = %d'd%d;  // illegal" % (isa.UADDR_BITS,
                                                          labels['illegal']))
    out.append("        prev    = %d'h%0*x;" % (w, nib, rq[labels['illegal']]))
    out.append("        illegal = 1'b1;")
    out.append('      end')
    out.append('    endcase')
    out.append('  end')
    out.append('')
    out.append('endmodule')
    out.append('')
    return '\n'.join(out)


def emit_loop(loop_patterns):
    """Opcode to "can this be the looped instruction" -- UM appendix A."""
    out = [BANNER, '',
           '// The loop mode instruction table, UM table A-1.',
           '//',
           '// Every one-word instruction whose memory operands use only (An),',
           '// (An)+ and -(An): with no instruction fetches happening there is',
           '// nowhere for an extension word to come from. The reasoning behind',
           '// two readings of that table is in tools/ucode/program.py.', '',
           'module rd68011_loop_rom (',
           '    input  logic [15:0] op,',
           '    output logic        is_loop',
           ');', '',
           '  always_comb begin',
           '    casez (op)']
    seen = {}
    for pat, mnem in loop_patterns:
        if pat in seen:
            continue
        seen[pat] = mnem
        out.append("      16'b%s: is_loop = 1'b1;  // %s"
                   % (pat.replace('-', '?'), mnem))
    out.append("      default: is_loop = 1'b0;")
    out.append('    endcase')
    out.append('  end')
    out.append('')
    out.append('endmodule')
    out.append('')
    return '\n'.join(out)


def emit_listing(words, labels, patterns):
    rev = {}
    for name, addr in labels.items():
        rev.setdefault(addr, []).append(name)

    enc_names = {}
    for name, _, enc in isa.FIELDS:
        if enc:
            enc_names[name] = {v: k for k, v in enc.items()}

    out = ['RD68011 microcode listing',
           '=========================',
           '',
           'Generated by tools/ucode/assemble.py. %d microwords of %d bits, '
           '%d opcode patterns.' % (len(words), isa.width(), len(patterns)),
           '']
    for i, (fields, comment) in enumerate(words):
        for name in sorted(rev.get(i, [])):
            out.append('%s:' % name)
        parts = []
        for name, _, _ in isa.FIELDS:
            # rq0/rq1 are not written by the microprogram: they are the
            # successors' own fields, copied here by fill_previews so the
            # sequencer has them a clock early. Printing them says nothing a
            # reader cannot get by looking at the successor, and says it on
            # every line.
            if name in ('rq0', 'rq1'):
                continue
            v = fields.get(name, isa.DEFAULTS[name])
            if v == isa.DEFAULTS[name] and name != 'next':
                continue
            if name in enc_names:
                parts.append('%s=%s' % (name, enc_names[name].get(v, v)))
            else:
                parts.append('%s=%d' % (name, v))
        out.append('  %3d  %-64s %s' % (i, ' '.join(parts),
                                        ('; ' + comment) if comment else ''))
    out.append('')
    out.append('Opcode patterns, in priority order')
    out.append('----------------------------------')
    for pat, target, mnem in patterns:
        out.append('  %s  %-10s -> %s (%d)' % (pat, mnem, target,
                                               labels[target]))
    out.append('')
    return '\n'.join(out)


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    old = None
    if os.path.exists(path):
        with open(path) as f:
            old = f.read()
    if old == text:
        return False
    with open(path, 'w') as f:
        f.write(text)
    return True


def main():
    isa.check()
    words, labels, fixups, patterns, fallthrough = program.build()
    words = resolve(words, labels, fixups, fallthrough)

    problems = check_patterns(patterns)
    if problems:
        for p in problems:
            print('error: ' + p)
        return 1

    if len(words) > (1 << isa.UADDR_BITS):
        print('error: %d microwords will not fit %d bits of address'
              % (len(words), isa.UADDR_BITS))
        return 1

    # Conditional branches land on an even/odd pair, so the target has to be
    # even for "next, or next+1 if the condition holds" to mean anything.
    for i, (fields, _) in enumerate(words):
        if fields.get('seq') == isa.SEQ['COND'] and fields.get('next', 0) % 2:
            print('error: microword %d branches conditionally to an odd '
                  'address' % i)
            return 1

    # Every microword's own successors' previews, once `next` is known.
    rq = fill_previews(words)
    steering, problems = check_arms(words, rq)
    problems = problems + check_ir_dst(words, rq)
    if problems:
        for p in problems:
            print('error: ' + p)
        return 1

    # The microword's two levels, and the proof that they rebuild it.
    tab = build_tables(words)
    problems = check_two_level(words, tab)
    if problems:
        for p in problems:
            print('error: ' + p)
        return 1

    changed = []
    for name, text in [
            ('rtl/gen/rd68011_ucode_pkg.sv', emit_pkg(labels, rq, tab)),
            ('rtl/gen/rd68011_ucode_rom.sv', emit_urom(words, tab)),
            ('rtl/gen/rd68011_uctl_rom.sv',
             emit_table('rd68011_uctl_rom', 'ctl', tab['default'][1],
                        tab['ctl'], tab['ctl_w'], CTL_W,
                        'The control fields of a microword, named by index.')),
            ('rtl/gen/rd68011_urq_rom.sv',
             emit_table('rd68011_urq_rom', 'rq', tab['default'][2],
                        tab['rq'], tab['rq_w'], RQ_W,
                        'Both of a microword\'s request previews, named by '
                        'index.')),
            ('rtl/gen/rd68011_decode_rom.sv', emit_decode(patterns, labels, rq)),
            ('rtl/gen/rd68011_loop_rom.sv', emit_loop(program.loop_patterns)),
            ('build/ucode.lst', emit_listing(words, labels, patterns))]:
        if write(os.path.join(ROOT, name), text):
            changed.append(name)

    stale = os.path.join(ROOT, 'rtl/gen/rd68011_ureq_rom.sv')
    if os.path.exists(stale):
        os.remove(stale)
        changed.append('rtl/gen/rd68011_ureq_rom.sv (removed)')

    print('%d microwords, %d bits wide (%d of request preview), '
          '%d opcode patterns, %d loop mode patterns'
          % (len(words), isa.width(), isa.req_width(), len(patterns),
             len(program.loop_patterns)))
    stored = (1 << isa.UADDR_BITS) * (isa.UADDR_BITS + tab['ctl_w'] +
                                      tab['rq_w'])
    flat = (1 << isa.UADDR_BITS) * isa.width()
    print('the store holds %d bits: %d x %d, plus %d x %d control patterns '
          'and %d x %d previews (%.2fx smaller than %d flat)'
          % (stored + len(tab['ctl']) * CTL_W + len(tab['rq']) * RQ_W,
             1 << isa.UADDR_BITS, isa.UADDR_BITS + tab['ctl_w'] + tab['rq_w'],
             len(tab['ctl']), CTL_W, len(tab['rq']), RQ_W,
             flat / float(stored + len(tab['ctl']) * CTL_W +
                          len(tab['rq']) * RQ_W), flat))
    irdst = [i for i, (f, _) in enumerate(words)
             if f.get('dst') == isa.DST['IR']]
    print('microwords that write ir from the ALU: %s '
          '(rd68011_seq.sv keeps them out of the address unit)'
          % (', '.join(str(i) for i in irdst) or 'none'))
    print('conditions that steer a bus request: %s (rd68011_seq.sv implements %s)'
          % (', '.join(steering) or 'none',
             ', '.join(isa.BUS_STEERING_CONDS)))
    if changed:
        print('updated: ' + ', '.join(changed))
    else:
        print('generated files already up to date')

    if '--check' in sys.argv and any(c.startswith('rtl/') for c in changed):
        print('error: checked-in generated files were stale')
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
